install:
- sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"
- sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
- sudo apt-get update
- sudo mkdir -p /var/lib/docker
- echo exit 101 | sudo tee /usr/sbin/policy-rc.d
- sudo chmod +x /usr/sbin/policy-rc.d
- sudo apt-get install -y slirp lxc lxc-docker aufs-tools cgroup-lite
- curl -sLo linux https://github.com/jpetazzo/sekexe/raw/master/uml
- chmod +x linux
script:
- ./linux quiet mem=2G rootfstype=hostfs rw eth0=slirp,,/usr/bin/slirp-fullbolt init=$(pwd)/uml.sh
  WORKDIR=$(pwd) HOME=$HOME DISTRO=$DISTRO
- bash -c '[ -a INSTALL_SUCCESS ]'
env:
  matrix:
  - DISTRO="arch"
  - DISTRO="centos6"
  - DISTRO="centos7"
  - DISTRO="debian-wheezy"
  - DISTRO="debian-squeeze"
  - DISTRO="fedora20"
  - DISTRO="ubuntu1204"
  - DISTRO="ubuntu1404"
deploy:
  provider: s3
  access_key_id: AKIAJNTOF3YZQSOTDSVA
  secret_access_key:
    secure: t55psMGNYGYwzlborJMkWo/kxXyHDM6vRfABQNo217VWSqqUdRXN0w5Bs2I29FWW+QaxNw+a15q6JMnblFFqi5zZRcHj2Zi61mjX21zcaCabA9d/yniKYRH3Fy4TEvBg1hf1MtTVDyqdZKrM+0jOb4dYkZeI8vAFjxw9u58/1RE=
  bucket: getpuppet.whilefork.com
  endpoint: "getpuppet.whilefork.com.s3-website-us-west-2.amazonaws.com"
  region: "us-west-2"
  on:
    repo: danieldreier/puppet-installer
    branch: master
