install:
- sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"
- sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
- sudo apt-get update
- sudo mkdir -p /var/lib/docker
- echo exit 101 | sudo tee /usr/sbin/policy-rc.d
- sudo chmod +x /usr/sbin/policy-rc.d
- sudo apt-get install -y slirp lxc lxc-docker aufs-tools cgroup-lite
- curl -sLo linux https://github.com/jpetazzo/sekexe/raw/master/uml
- chmod +x linux
script:
- ./linux quiet mem=2G rootfstype=hostfs rw eth0=slirp,,/usr/bin/slirp-fullbolt init=$(pwd)/uml.sh
  WORKDIR=$(pwd) HOME=$HOME DISTRO=$DISTRO
- ls -la
- bash -c '[ -a INSTALL_SUCCESS ]'
- bash -c '[ -a PUPPET_SUCCESS ]'
- bash -c '[ -a PUPPET_RESOURCE_SUCCESS ]'
- bash -c '[ -a FACTER_SUCCESS ]'
- curl -Lo travis_after_all.py https://raw.githubusercontent.com/dmakhno/travis_after_all/b7172bca92d6dcfcec2a0eacdf14eb5f3a1ad627/travis_after_all.py

env:
  matrix:
  - DISTRO="arch"
  - DISTRO="centos6"
  - DISTRO="centos7"
  - DISTRO="debian-wheezy"
  - DISTRO="debian-squeeze"
  - DISTRO="fedora20"
  - DISTRO="ubuntu1004"
  - DISTRO="ubuntu1204"
  - DISTRO="ubuntu1310"
  - DISTRO="ubuntu1404"
after_success:
- python travis_after_all.py
- export $(cat .to_export_back)
- |
  if [ "$BUILD_LEADER" = "YES" ]; then
    if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
      echo "All Succeded! PUBLISHING..."
    else
      echo "Some Failed"
    fi
  fi
after_failure:
- python travis_after_all.py
- export $(cat .to_export_back)
- |
  if [ "$BUILD_LEADER" = "YES" ]; then
    if [ "$BUILD_AGGREGATE_STATUS" = "others_failed" ]; then
      echo "All Failed"
    else
      echo "Some Failed"
    fi
  fi
after_script:
- echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
deploy:
  - provider: s3
    access_key_id: AKIAJNTOF3YZQSOTDSVA
    secret_access_key:
      secure: t55psMGNYGYwzlborJMkWo/kxXyHDM6vRfABQNo217VWSqqUdRXN0w5Bs2I29FWW+QaxNw+a15q6JMnblFFqi5zZRcHj2Zi61mjX21zcaCabA9d/yniKYRH3Fy4TEvBg1hf1MtTVDyqdZKrM+0jOb4dYkZeI8vAFjxw9u58/1RE=
    bucket: getpuppet.whilefork.com
    endpoint: "getpuppet.whilefork.com.s3-website-us-west-2.amazonaws.com"
    region: "us-west-2"
    on:
      repo: danieldreier/puppet-installer
      branch: master
      condition: $BUILD_LEADER = YES && $BUILD_AGGREGATE_STATUS = "others_succeeded"
  - provider: releases
    api_key:
      secure: Ec6dUUNVTd3rU7RXdYVK13gUw8wCpjz2cwVnAWYjnWiFTC4OyV9SGKM2JG1yQsEfbLLoAhZ1/tRJP0VlvwqRlr82OACqoeTaBCZBPCn9pdW+QYf+4SK7iSMcrLeewlyd+DNZ65+2ox/cuRE7/2iOP33m+4fBXp7mk59bwSkq2s0=
    file: install_puppet.sh
    on:
      tags: true
      all_branches: true
      repo: danieldreier/puppet-installer
      branch: master
      condition: $BUILD_LEADER = YES && $BUILD_AGGREGATE_STATUS = "others_succeeded"
